# -*- coding: utf-8 -*-
"""Cópia de [Imersão Python] Aula 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ehchnYSd_X-CbOvICztY96eB9cT01gc
"""

import pandas as pd

caminho = 'C:/Users/lucas.lourenco/OneDrive - Iteris Consultoria e Software/Documentos/Estudos/Alura---Imersao-Python-2024/Aula2/acoes_pura.xlsx'

df_principal = pd.read_excel(caminho, sheet_name="Principal")
df_principal

df_total_acoes = pd.read_excel(caminho, sheet_name="Total_de_acoes")
df_total_acoes

df_ticker = pd.read_excel(caminho, sheet_name="Ticker")
df_ticker

df_chatgpt = pd.read_excel(caminho, sheet_name="Chatgpt")
df_chatgpt